name       = "iptv-live"
main       = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding         = "LIVE_CHANNELS"
id              = "f1e124a636e34b64a477ad48ba0ccc72"
preview_id      = "f1e124a636e34b64a477ad48ba0ccc72"
